version: "3"
services:
  app:
    restart: always
    build: ./
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - app-data:/app/storage
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7.2.5
    restart: always

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  app-data:
