/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface PasswordResets {
  created_at: Generated<Date>;
  email: string;
  token: string;
}

export interface Users {
  created_at: Generated<Date>;
  email: string;
  id: Generated<number>;
  name: string;
  password: string;
  updated_at: Generated<Date>;
}

export interface DB {
  password_resets: PasswordResets;
  users: Users;
}
